name: Community
on: 
  issues:
    types: [opened, edited, milestoned]
  pull_request_target:
    types: [opened]
  workflow_dispatch:

jobs:
  labeler:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest

    steps:
    - name: Import Secrets
      uses: Infisical/secrets-action@v1.0.12
      with:
        method: "oidc"
        env-slug: "dev"
        project-slug: "github-g0zh"
        identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{env.NGLBOT}}