name: PR Reviewer
on:
  pull_request_target:
    types: [opened]

jobs:
  review:
    permissions:
        contents: read
        id-token: write
    name: Review PR
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: Infisical/secrets-action@v1.0.11
        with:
          method: "oidc"
          env-slug: "dev"
          project-slug: "github-g0zh"
          identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
      - name: Request Reviewer
        uses: actions/github-script@v6
        with:
          github-token: ${{env.NGLBOT}}
          script: |
            async function main(){
            async function getAuthor(owner, repo, pull_number) {
              try {
                const { data: pullRequest } = await github.rest.pulls.get({
                  owner: owner,
                  repo: repo,
                  pull_number: pull_number,
                });
                return pullRequest.user.login;
              } catch (error) {
                console.error("Error fetching pull request:", error);
                return null;
              }
            }
            const author = await getAuthor(context.repo.owner, context.repo.repo, context.issue.number)
            if (!author.includes('hi5a')){
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Requesting review from @hi5a \n___ \n###### This comment was generated by @nglbot"
              })
              github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                reviewers: ['hi5a']
              });
            }
            }
            main()
      - name: Approve Pull Request
        if: ${{ always() }}
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{env.NGLBOT}}
          number: ${{ github.event.number }}
